### ISSUE TITLE
Поле оцениваемый берется из логина сотрудника

### ISSUE THREAD

**Issue by isaidashev** [olemskoi/redmine_centosadmin_rating#9]
Поле оцениваемый берется из логина сотрудника. Можно сделать чтобы использовался имя и фамилия в системе?

**Comment by alexar1987** [comment]
views/centos/rating/issues/_form.html.slim

{ |u| [u.login, u.id] }

заменить на 

{ |u| [u.name, u.id] }

**Comment by max-konin** [comment]
Думаю можно это вынести в конфигурации

**Comment by constXife** [comment]
Мы переделали на name. Не вижу смысла использовать login сотрудника, это больше техническая информация, чем справочная.
